notification :off

group :development do

  # Only run Compass if we have a config.rb file in place.
  if File.exists?("config.rb")
    # Compile on start.
    puts `compass compile --time --quiet`

    # https://github.com/guard/guard-compass
    guard :compass do
      watch(%r{.+\.s[ac]ss$})
    end
  end

  ## Uncomment this if you wish to use auto converting svg to png
  guard :shell do
    puts 'Monitoring svg files.'

    watch (%r{.[\w-]+\.svg}) do |m|
      svgfile = m[0]
      pngfile = svgfile.gsub(/svg$/, 'png')
      png = pngfile.gsub(/(\/[\w-]+.png)$/, '/png')
      png_2x = pngfile.gsub(/(\/[\w-]+.png)$/, '/png_2x')
      png_normal = pngfile.gsub(/(\/[\w-]+.png)$/, '/png\1')
      png_retina = pngfile.gsub(/(\/[\w-]+.png)$/, '/png_2x\1')

      puts 'Change detected: ' + svgfile
      if File.file?(svgfile)
        system "mkdir -p #{png}"
        system "mkdir -p #{png_2x}"
        system "convert -background none -density 72 #{svgfile} #{png_normal}"
        system "convert -background none -density 144 #{svgfile} #{png_retina}"
      else
        system "rm #{png_normal}"
        system "rm #{png_retina}"
      end
    end
  end

  ## Uncomment this if you wish to clear the theme registry every time you
  ## change one of the relevant theme files.
  #guard :shell do
  #  puts 'Monitoring theme files.'
  #
  #  watch(%r{.+\.(php|inc|info)$}) { |m|
  #    puts 'Change detected: ' + m[0]
  #    `drush cache-clear theme-registry`
  #    puts 'Cleared theme registry.'
  #  }
  #end

  # https://github.com/guard/guard-livereload.
  # Ignore *.normalize.scss to prevent flashing content when re-rendering.
  guard :livereload do
    watch(%r{^((?!\.normalize\.).)*\.(css|js)$})
  end

end
